import type { AnimeRow } from "@/lib/supabase/types";

const now = "2026-07-01T00:00:00.000Z";

function anime(row: {
  id: number;
  slug: string;
  title: string;
  cover: string;
  score: number;
  year: number;
  genres: string[];
  color?: string;
}): AnimeRow {
  return {
    id: `anilist-${row.id}`,
    anilist_id: row.id,
    slug: row.slug,
    title_romaji: row.title,
    title_english: row.title,
    title_native: null,
    synopsis: null,
    cover_image: row.cover,
    banner_image: null,
    dominant_color: row.color ?? "#A8B8AE",
    format: "TV",
    status: "RELEASING",
    episodes: null,
    duration: null,
    season: "SUMMER",
    season_year: row.year,
    genres: row.genres,
    studios: [],
    source: null,
    anilist_score: row.score,
    animelot_score: null,
    popularity: 0,
    trailer_url: null,
    external_links: {},
    next_airing_ep: null,
    next_airing_at: null,
    created_at: now,
    updated_at: now,
  };
}

export const browseFallbackAnime: AnimeRow[] = [
  anime({
    id: 197715,
    slug: "the-villager-of-level-999",
    title: "The Villager of Level 999",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx197715-KLFLxU24U1uL.png",
    score: 8.1,
    year: 2026,
    genres: ["Adventure", "Fantasy"],
  }),
  anime({
    id: 21,
    slug: "one-piece",
    title: "ONE PIECE",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21-ELSYx3yMPcKM.jpg",
    score: 8.7,
    year: 1999,
    genres: ["Action", "Adventure"],
  }),
  anime({
    id: 178789,
    slug: "smoking-behind-the-supermarket-with-you",
    title: "Smoking Behind the Supermarket with You",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx178789-hNXjKFzUq7mk.jpg",
    score: 7.9,
    year: 2026,
    genres: ["Romance", "Slice of Life"],
  }),
  anime({
    id: 196187,
    slug: "saga-of-tanya-the-evil-season-2",
    title: "Saga of Tanya the Evil Season 2",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx196187-cXhET893v3Ag.png",
    score: 8.0,
    year: 2026,
    genres: ["Action", "Fantasy"],
  }),
  anime({
    id: 135865,
    slug: "bleach-thousand-year-blood-war",
    title: "BLEACH: Thousand-Year Blood War",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx135865-T7XIPMAbqcxN.png",
    score: 8.6,
    year: 2022,
    genres: ["Action", "Supernatural"],
  }),
  anime({
    id: 185874,
    slug: "puella-magi-madoka-magica",
    title: "Puella Magi Madoka Magica",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx185874-aU3e6tBT6wwA.jpg",
    score: 8.4,
    year: 2026,
    genres: ["Drama", "Fantasy"],
  }),
  anime({
    id: 133007,
    slug: "i-want-to-love-you-till-your-dying-day",
    title: "I Want to Love You Till Your Dying Day",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx133007-5gOUXDvzxy9S.jpg",
    score: 7.8,
    year: 2026,
    genres: ["Drama", "Romance"],
  }),
  anime({
    id: 187260,
    slug: "trapped-in-a-dating-sim",
    title: "Trapped in a Dating Sim",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx187260-WW5RBa5NINRP.jpg",
    score: 7.5,
    year: 2026,
    genres: ["Comedy", "Fantasy"],
  }),
  anime({
    id: 159309,
    slug: "sparks-of-tomorrow",
    title: "Sparks of Tomorrow",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx159309-wRfh9O1odrDJ.jpg",
    score: 7.7,
    year: 2026,
    genres: ["Drama", "Sci-Fi"],
  }),
  anime({
    id: 5114,
    slug: "fullmetal-alchemist-brotherhood",
    title: "Fullmetal Alchemist: Brotherhood",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx5114-nSWCgQlmOMtj.jpg",
    score: 9.0,
    year: 2009,
    genres: ["Action", "Adventure"],
  }),
  anime({
    id: 20954,
    slug: "a-silent-voice",
    title: "A Silent Voice",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20954-f30bHMXa5Qoe.jpg",
    score: 8.8,
    year: 2016,
    genres: ["Drama", "Romance", "Slice of Life"],
  }),
  anime({
    id: 20,
    slug: "naruto",
    title: "Naruto",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20-YJvLbgJQPCoI.jpg",
    score: 7.9,
    year: 2002,
    genres: ["Action", "Adventure"],
  }),
  anime({
    id: 101922,
    slug: "demon-slayer-kimetsu-no-yaiba",
    title: "Demon Slayer: Kimetsu no Yaiba",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101922-WBsBl0ClmgYL.jpg",
    score: 8.3,
    year: 2019,
    genres: ["Action", "Supernatural"],
  }),
  anime({
    id: 16498,
    slug: "attack-on-titan",
    title: "Attack on Titan",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx16498-C6FPmWm59CyP.jpg",
    score: 8.5,
    year: 2013,
    genres: ["Action", "Drama", "Fantasy"],
  }),
  anime({
    id: 1535,
    slug: "death-note",
    title: "Death Note",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx1535-kUgkcrfOrkUM.jpg",
    score: 8.4,
    year: 2006,
    genres: ["Mystery", "Psychological"],
  }),
  anime({
    id: 124194,
    slug: "jujutsu-kaisen",
    title: "JUJUTSU KAISEN",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx124194-TJlqMMR7BGn9.jpg",
    score: 8.5,
    year: 2020,
    genres: ["Action", "Supernatural"],
  }),
];
